### PR TITLE
Nav items clickable with middle mouse button

### LINKED ISSUE #270: Menu navigation items are not clickable with middle mouse button
# Steps to reproduce
1. Go to any page
2. Click with middle mouse button on any menu navigation item

# Experienced
Clicking with middle mouse button doesn't open the menu navigation item in a new tab. A power user feature I use a lot in my browser.

# Expected
When clicking with the middle mouse button on a menu navigation item it will open the link in a new tab in the browser.

### PR DESCRIPTION
**Pull request by Timo-DK**
Fixes #270 

Tested navigation and it is still working. Of course clicking with middle mouse button causes the Next app to reload as we are not using the AppRouter.
image

image

---

This pull request refactors and enhances the navigation component in `components/navigation.tsx`. Key changes include introducing a `NavItem` interface for better type safety, refactoring the `OnHoverNav` function to handle mouse events more robustly, and improving the structure of the mobile navigation dropdown. These changes improve code readability, maintainability, and user interaction.

### Type Safety and Code Organization:
* Introduced a `NavItem` interface to define the structure of navigation items, including optional `subLinks`, improving type safety and clarity (`[components/navigation.tsxL3-R19](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e8ddcf7f480faf1ad2481286cL3-R19)`).

### Mouse Event Handling:
* Added a `handleMouseDown` function to manage mouse interactions, supporting middle-click to open links in new tabs and left-click for navigation (`[components/navigation.tsxL140-R176](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e8ddcf7f480faf1ad2481286cL140-R176)`).

### Refactoring of `OnHoverNav`:
* Refactored `OnHoverNav` to use the `NavItem` interface and updated the logic for rendering navigation buttons and menus, ensuring consistent behavior across links with and without sublinks (`[[1]](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e8ddcf7f480faf1ad2481286cL140-R176)`, `[[2]](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e8ddcf7f480faf1ad2481286cL153-L174)`).

### Mobile Navigation Improvements:
* Replaced inline click handlers with a reusable `getButtonProps` function for generating button properties in the mobile dropdown, enhancing code reuse and reducing duplication (`[components/navigation.tsxR209-R220](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e8ddcf7f480faf1ad2481286cR209-R220)`).

### Simplified Mapping Logic:
* Simplified the mapping of `navItems` to components in the main navigation bar by spreading the `NavItem` properties directly into the `OnHoverNav` component (`[components/navigation.tsxL202-R232](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e8ddcf7f480faf1ad2481286cL202-R232)`).

### CODE REVIEW

File: components/navigation.tsx [hunk 1]
```diff
@@ -137,41 +144,50 @@ const customNavDrop = {
     }
 }
 
-function OnHoverNav({ link, label, subLinks }: { link: string, label: string, subLinks: { subLink: string, label: string }[] | undefined }) {
+function handleMouseDown(e: React.MouseEvent, href: string, router: AppRouterInstance) {
```
Comment (Sludging) [inline components/navigation.tsx:147]: nitpicky comment: Should we maybe pass in the `push` function instead of the entire `router` instance?

I forgot the name of the principle/concept of not exposing information to a function that isn't needed by it, but in reality I just don't like the `AppRouterInstance` out of no real reason but aesthetics

**Review by Sludging — APPROVED** [review]
Appreciate you doing it cleanly with adding proper interfaces and consilidating code duplication.

Left really minor comments / question but no issue with merging this in when ever you want.

Thank you for your contribution!

File: components/navigation.tsx (hunk 1 above)
Comment (Timo-DK) [reply components/navigation.tsx:147]: Yes I know what principle you mean (also forgot the name 🙈 ), while I do agree with your statement, it depends on the context. In this case it would be better to pass in the `AppRouterInstance` object because this way we are able to enforce that this function only works with this type.

If I would follow this principle here and just pass in the push function, I would have to add a void function callback parameter, e.g.:
```
function handleMouseDown(e: React.MouseEvent, href: string, push: () => void)
```

This allows the function caller to determine what the implementation of the push callback would be. This causes leaking implementation details of `handleMouseDown` and shifts the responsibility of how the push works (an implementation detail) to the function caller.

File: components/navigation.tsx [hunk 2]
```diff
@@ -137,41 +144,50 @@ const customNavDrop = {
...
+        router.push(href);
+    }
+}
+
+function OnHoverNav({ link, label, subLinks }: NavItem) {
     const pathname = usePathname();
     const router = useRouter();
 
-    if (subLinks) {
+    if (!subLinks) {
```
[the remark this answers is not in the document]
Comment (Sludging) [reply components/navigation.tsx:163]: Yeah it was always an early return, so I was just curious haha.

But yeah returning the "smaller" code segment sometimes feel fine.

I don't really mind either way so no need to change
